colors:
  primary: '#f0a8e4'
  # bg: "#F5F5F5"
  selection_bg: '#8e71c1' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

social:
  - name: GitHub
    link: https://github.com/Hatsushigure
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:Hatsushigure_c@163.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: Twitter
    link: https://twitter.com/Hatsushigure_c
    icon: ri:twitter-line
    color: '#1da1f2'
  - name: Telegram
    link: https://t.me/Hatsushigure
    icon: ri:telegram-line
    color: '#0088CC'

banner:
  enable: true
  title: åˆæ™‚é›¨çœŸæ­£çš„å¿ƒçµå°çª
  border: true
  cloud:
    enable: true
    color: #66b1f2
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: true
  content: è¿™æ˜¯æˆ‘çš„ç§äººåšå®¢ï¼Œå¯èƒ½å«æœ‰å¤§é‡ emo å†…å®¹ï¼Œè°¨æ…é˜…è¯»ã€‚

bg_image:
  enable: true
  url: https://pic.imgdb.cn/item/654f9d88c458853aefea7969.jpg
  # dark:
  blur: 8px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

# _config.yun.yml
medium_zoom: true

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

avatar:
  enable: true
  url: https://pic.imgdb.cn/item/65e8502a9f345e8d03cc0c66.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜™
    message: æ¬¢è¿ä½ ï¼Œç¥æ„¿ä½ å¹¸ç¦åœ°èµ°è¿‡æ¯ä¸€å¤©

menu:
  home:
    path: .
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: ri:settings-line

pages:
  - name: å›åˆ°ä¸»ç«™
    url: https://hatsushigure.github.io
    icon: ic:baseline-exit-to-app
    color: "#f2415c"

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

codeblock:
  copy_btn: true

reward:
  enable: false

footer:
  since: 2023
  icon:
    name: ri:cloud-line
    animated: true
    color: '#0078E7'

wordcloud:
  enable: true

wordcount:
  enable: true
  count: true
  time: true

say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn
